version: '3.8'
services:
  db:
    image: postgres:15
    container_name: notifyhub_db
    environment:
      - POSTGRES_USER=lucca
      - POSTGRES_PASSWORD=shizuru
      - POSTGRES_DB=notifyhub
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    container_name: notifyhub_pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "8081:80"
    depends_on:
      - db